# 数据库连接配置
database:
  # 默认数据库类型
  default_type: mysql
  
  # MySQL数据库配置
  mysql:
    dev:
      host: 8.133.246.113
      port: 3306
      user: bgtech
      password: Zly689258..
      database: bgpay
      charset: utf8mb4
      autocommit: true
    test:
      host: 8.133.246.113
      port: 3306
      user: bgtech
      password: Zly689258..
      database: bgpay
      charset: utf8mb4
      autocommit: true
    prod:
      host: prod-mysql.example.com
      port: 3306
      user: prod_user
      password: prod_pass
      database: prod_db
      charset: utf8mb4
      autocommit: true
  
  # PostgreSQL数据库配置
  postgresql:
    dev:
      host: 8.133.246.113
      port: 5432
      user: postgres
      password: Postgres@123456
      database: jiangyangpay
      autocommit: true
    test:
      host: 8.133.246.113
      port: 5432
      user: postgres
      password: Postgres@123456
      database: jiangyangpay
      autocommit: true
    prod:
      host: prod-postgres.example.com
      port: 5432
      user: prod_user
      password: prod_pass
      database: prod_db
      autocommit: true
  
  # Redis数据库配置
  redis:
    dev:
      host: 8.133.246.113
      port: 6379
      password: 5z25u2sk
      db: 0
    test:
      host: 8.133.246.113
      port: 6379
      password: 5z25u2sk
      db: 1
    prod:
      host: prod-redis.example.com
      port: 6379
      password: prod_redis_pass
      db: 0
  
  # SQLite数据库配置
  sqlite:
    dev:
      database: dev.db
    test:
      database: test.db
    prod:
      database: prod.db 